version: '3.7'
services:
  postgres:
    container_name: postgres_mimic
    image: tkolleh/mimic-iii:latest
    environment:
      # CONTAINR_HOSTNAME: ${CONTAINER_HOSTNAME:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      MIMIC_PASSWORD: ${MIMIC_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data
    volumes:
       - ${DB_DIR-./database/postgresDB}:/var/lib/postgresql/data
       - ${MIMIC_DATA_DIR-./database/MIMICData}:/var/lib/postgresql/mdata
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  postgraphile:
    image: graphile/postgraphile:latest
    restart: unless-stopped
    ports:
    - "5000:5000"
    networks:
      - postgres
    links:
      - "postgres:database"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL-postgres://postgres:password@postgres:5432/mimic}
    command: ["postgraphile", "--connection", $DATABASE_URL, "--host", "0.0.0.0", "--port", "5000", "--schema", "mimic"]        

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
